Traceback (most recent call last):
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
    mainwindow = run_spyder(app, options, args)
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\spyder\app\mainwindow.py", line 2923, in run_spyder
    main.post_visible_setup()
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\spyder\app\mainwindow.py", line 1224, in post_visible_setup
    self.projects.reopen_last_project()
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\spyder\plugins\projects.py", line 309, in reopen_last_project
    save_previous_files=False)
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\spyder\plugins\projects.py", line 262, in open_project
    self.current_active_project = EmptyProject(path)
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\spyder\widgets\projects\type\__init__.py", line 63, in __init__
    self.create_project_config_files()
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\spyder\widgets\projects\type\__init__.py", line 94, in create_project_config_files
    version=version)
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\spyder\widgets\projects\config.py", line 97, in __init__
    raw_mode=True, remove_obsolete=True)
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\spyder\config\user.py", line 202, in __init__
    self.load_from_ini()
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\spyder\config\user.py", line 252, in load_from_ini
    self.read(self.filename(), encoding='utf-8')
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\configparser.py", line 696, in read
    self._read(fp, filename)
  File "D:\Users\47020753817\Downloads\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from 'D:/Users/47020753817/Downloads/WinPython-64bit-3.5.3.1Qt5/AJNA/ajna\\.spyproject\\workspace.ini' [line  7]: option 'save_history' in section 'workspace' already exists
